# Generated by Django 4.0.5 on 2022-07-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la noticia')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titolo de la noticia')),
                ('encabezado_noticia', models.CharField(max_length=50, verbose_name='Encabezado de la noticia')),
                ('cuerpo_noticia', models.CharField(max_length=250, verbose_name='Cuerpo de la noticia')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut de periodista')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre del periodista')),
                ('correo', models.EmailField(max_length=200, verbose_name='Correo electronico de periodista')),
            ],
        ),
    ]
