# Generated by Django 4.0.5 on 2022-07-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Categoria de la noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo_noticia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='encabezado_noticia',
            field=models.CharField(max_length=250, verbose_name='Encabezado de la noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Titolo de la noticia'),
        ),
    ]
