# Generated by Django 4.0.5 on 2022-07-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticia_categoria_alter_noticia_cuerpo_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='idNoticia',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la noticia'),
        ),
    ]
